
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: planetaryballistics
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary:  Simple gravitational game ;)  # 79 char long summary
  description: |
    Your moons are shotting at you... Nukes! Defend yourself and your allied satellites in this planetary shooter!
    Select the plaent or the satellite you wanna use as lunching base, aim and shoot in this very intuitive game.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  apps:
    planetaryballistics:
      command: love .
  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
